server:
  port: 8080

spring:
  application:
    name: sample
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
jwt:
  secret-key: "your-secret-key"  # Replace with a more secure key in production
  expiration-time: 86400000  # Token expiration time in milliseconds (1 day)